language: python
python: "2.7"
cache:
    directories:
        - $HOME/.cache/pip
install:
    - pip uninstall -y pytest
    - pip install -r requirements/local.txt
    - pip install coveralls
script:
    - cd acornaccounting && py.test && cd ..
after_success:
    - mv -f acornaccounting/.coverage . && coveralls
